apiVersion: v1
kind: Namespace
metadata:
  name: fn
---
apiVersion: v1
kind: Service
metadata:
  namespace: fn
  name: fn-service
  labels:
    app: fn
    role: fn-service
spec:
  type: NodePort
  ports:
  - name: fn-service
    port: 8080
    targetPort: 8080
    nodePort: 32180
  - name: fn-ui
    port: 80
    targetPort: 80
    nodePort: 32080
  selector:
    app: fn
    role: fn-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: fn
  name: fn-service
spec:
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: fn
        role: fn-service
    spec:
      containers:
      - name: fn-service
        image: fnproject/fnserver
        imagePullPolicy: Always
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080
        env:
          - name: LOG_LEVEL
            value: debug
